// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    app: "lartop50",
    project_key: function(app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":project";
    },
    project_description: function(id, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":project:" + id + ":description";
    },
    project_clusters: function(id, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":project:" + id + ":clusters";
    },
    user_projects: function(uid, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":uid:" + uid + ":projects";
    },
    cluster_key: function(app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":cluster";
    },
    cluster_description: function(id, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":cluster:" + id + ":description";
    },
    cluster_components: function(id, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":cluster:" + id + ":components";
    },
    cluster_linpack: function(id, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":cluster:" + id + ":linpack";
    },
    component_key: function(app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":component";
    },
    component_description: function(id, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":component:" + id + ":";
    },
    linpack_key: function(app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":linpack";
    },
    linpack_description: function(id, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":linpack:" + id;
    }
  };

}).call(this);
