// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    app: "lartop50",
    cluster_key: function(app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":cluster";
    },
    cluster: function(id, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":cluster:" + id + ":description";
    },
    clusters: function(uid, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":uid:" + uid + ":clusters";
    },
    component_key: function(app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":component";
    },
    component: function(id, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":cluster:component:" + id + ":";
    },
    components: function(id, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":cluster:" + id + ":components";
    },
    linpack_key: function(app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":linpack";
    },
    linpack: function(id, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":cluster:linpack:" + id + ":";
    },
    linpacks: function(id, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":cluster:" + id + ":linpack";
    }
  };

}).call(this);
