// Generated by CoffeeScript 1.3.3
(function() {
  var SMTPtransport, nodemailer;

  nodemailer = require("nodemailer");

  SMTPtransport = nodemailer.createTransport("SMTP", {
    host: "smtp.gmail.com",
    secureConnection: true,
    port: 465,
    auth: {
      user: "samuelbustamant@gmail.com",
      pass: "bahiaInglesa09"
    }
  });

  module.exports = {
    send: function(to, subject, text, html, callback) {
      var mailOptions;
      mailOptions = {
        from: "Samuel Bustamante <samuelbustamant@gmail.com>",
        to: to,
        subject: subject,
        text: text,
        html: html
      };
      return SMTPtransport.sendMail(mailOptions, function(error) {
        if (error) {
          return callback(error);
        } else {
          return callback(null);
        }
      });
    }
  };

}).call(this);
