// Generated by CoffeeScript 1.3.3
(function() {
  var auth, isEmpty, keys_auth, keys_submissions, redis;

  auth = require("../auth/auth");

  redis = require("../redis/client");

  keys_auth = require("../auth/keys");

  keys_submissions = require("../submissions/keys");

  isEmpty = function(obj) {
    var i, response, _i, _len;
    response = true;
    for (_i = 0, _len = obj.length; _i < _len; _i++) {
      i = obj[_i];
      response = false;
    }
    return response;
  };

  exports.index = function(req, res) {
    return auth.is_authenticated(req, function(user) {
      if (!user) {
        res.redirect('/ingresar');
        return;
      }
      return redis.client.HGETALL(keys_auth.profile(user), function(error, profile) {
        if (error) {
          res.end('internal error', 500);
        }
        return redis.client.SMEMBERS(keys_submissions.user_centers(user), function(error, members) {
          var cmds, member, _i, _len;
          cmds = [];
          for (_i = 0, _len = members.length; _i < _len; _i++) {
            member = members[_i];
            cmds.push(['HGETALL', keys_submissions.center_description(member)]);
          }
          return redis.client.multi(cmds).exec(function(error, projects) {
            if (isEmpty(projects)) {
              projects = null;
            }
            return res.render('index', {
              profile: profile,
              centers: projects
            });
          });
        });
      });
    });
  };

}).call(this);
