// Generated by CoffeeScript 1.3.3
(function() {
  var auth, client, redis;

  redis = require("redis");

  auth = require("../auth/auth");

  client = redis.createClient();

  exports.index = function(req, res) {
    return auth.is_authenticated(req, function(user) {
      if (user) {
        res.redirect('/');
        return;
      }
      return res.render('login');
    });
  };

}).call(this);
