// Generated by CoffeeScript 1.3.3
(function() {
  var client, keys, redis;

  keys = require("./keys");

  redis = require("redis");

  client = redis.createClient();

  exports.create = function(req, res) {
    var errors, key;
    req.assert("key").is(/^[0-9a-z]{32}$/);
    errors = req.validationErrors();
    if (errors) {
      res.json({
        message: "invalid parameters",
        errors: errors
      }, 400);
      return;
    }
    key = req.body.key;
    return client.GET(keys.activate(key), function(error, uid) {
      if (error) {
        res.json({
          message: "internal error"
        }, 500);
        return;
      }
      if (!uid) {
        res.json({
          message: "key not found"
        }, 404);
        return;
      }
      return client.SET(keys.active(uid), true, function(error) {
        if (error) {
          res.json({
            message: "internal error"
          }, 500);
          return;
        }
        return client.DEL(keys.activate(key), function(error) {
          if (error) {
            res.json({
              message: "internal error"
            }, 500);
          }
          return res.json({
            message: "activation successful"
          }, 200);
        });
      });
    });
  };

}).call(this);
