// Generated by CoffeeScript 1.3.3
(function() {
  var client, keys, redis, validate;

  keys = require("./keys");

  redis = require("redis");

  validate = require("../validate/validate");

  client = redis.createClient();

  exports.show = function(req, res) {
    var data, options;
    options = [['activate', 'md5']];
    data = validate.validate(options, req.params);
    if (!data) {
      res.json({}, 400);
      return;
    }
    return client.GET(keys.activate(data.activate), function(error, uid) {
      if (error) {
        res.json({}, 500);
        return;
      }
      if (!uid) {
        res.json({}, 404);
        return;
      }
      return client.SET(keys.active(uid), true, function(error) {
        if (error) {
          res.json({}, 500);
          return;
        }
        return client.DEL(keys.activate(data.activate), function(error) {
          if (error) {
            res.json({}, 500);
          }
          return res.json({}, 200);
        });
      });
    });
  };

}).call(this);
