// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    is_authenticated: function(req, callback) {
      if (req.session.auth) {
        return callback(req.session.auth.uid);
      } else {
        return callback(null);
      }
    },
    login: function(req, uid) {
      req.session.auth = {};
      return req.session.auth.uid = uid;
    },
    logout: function(req) {
      return delete req.session.auth;
    }
  };

}).call(this);
