// Generated by CoffeeScript 1.3.3
(function() {
  var emails;

  emails = require("../emails/emails");

  module.exports = {
    send_activate_key: function(to, key, callback) {
      var html, subject, text;
      subject = "Email de Activación";
      text = key;
      html = "<p>" + key + "</p>";
      return emails.send(to, subject, text, html, function(error) {
        if (error) {
          return callback(error);
        } else {
          return callback(null);
        }
      });
    }
  };

}).call(this);
