// Generated by CoffeeScript 1.3.3
(function() {
  var auth;

  auth = require("./auth");

  exports.create = function(req, res) {
    return auth.is_authenticated(req, function(user) {
      if (!user) {
        auth.logout(req);
        return res.json({
          message: "logout successful"
        }, 200);
      } else {
        return res.json({
          message: "not authenticated"
        }, 401);
      }
    });
  };

}).call(this);
