// Generated by CoffeeScript 1.3.3
(function() {
  var auth, client, keys, redis;

  redis = require("redis");

  auth = require("../auth/auth");

  keys = require("../auth/keys");

  client = redis.createClient();

  client['Multi'] = client.multi();

  exports.index = function(req, res) {
    return auth.is_authenticated(req, function(user) {
      if (!user) {
        res.json({
          message: "not authenticated"
        }, 401);
        return;
      }
      return client.HGETALL(keys.profile(user), function(error, profile) {
        if (error) {
          res.json({
            message: "internal error"
          }, 500);
          return;
        }
        return res.json(profile, 200);
      });
    });
  };

}).call(this);
