// Generated by CoffeeScript 1.3.3
(function() {
  var client, email, keys, md5, redis, validate;

  md5 = require("MD5");

  keys = require("./keys");

  redis = require("redis");

  email = require("./email");

  validate = require("../validate/validate");

  client = redis.createClient();

  exports.create = function(req, res) {
    var data, options;
    options = [["email", "email"], ["password", "password"], ["name", "char"], ["organization", "char"]];
    data = validate.validate(options, req.body);
    if (!data) {
      res.json({
        message: "invalid parameters"
      }, 400);
      return;
    }
    return client.GET(keys.user(data.email), function(error, uid) {
      if (uid) {
        res.json({
          message: "email is already in use"
        }, 410);
        return;
      }
      return client.INCR(keys.key(), function(error, uid) {
        if (error) {
          res.json({
            message: "internal error"
          }, 500);
          return;
        }
        return client.SET(keys.user(data.email), uid, function(error) {
          if (error) {
            res.json({
              message: "internal error"
            }, 500);
            return;
          }
          return client.SET(keys.password(uid), md5(data.password), function(error) {
            var profile;
            if (error) {
              res.json({
                message: "internal error"
              }, 500);
              return;
            }
            profile = {
              name: data.name,
              organization: data.organization
            };
            return client.HMSET(keys.profile(uid), profile, function(error) {
              if (error) {
                res.json({
                  message: "internal error"
                }, 500);
                return;
              }
              return client.SET(keys.active(uid), false, function(error) {
                var key;
                if (error) {
                  res.json({
                    message: "internal error"
                  }, 500);
                  return;
                }
                key = md5(Date() + data.email);
                return client.SET(keys.activate(key), uid, function(error) {
                  if (error) {
                    res.json({
                      message: "internal error"
                    }, 500);
                    return;
                  }
                  return email.send_activate_key(data.email, key, function(error) {
                    if (error) {
                      return res.json({
                        message: "internal error"
                      }, 500);
                    } else {
                      return res.json({
                        message: "successful registration"
                      }, 200);
                    }
                  });
                });
              });
            });
          });
        });
      });
    });
  };

}).call(this);
