// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    app: "lartop50",
    center_key: function(app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":center";
    },
    center_description: function(id, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":center:" + id + ":description";
    },
    center_systems: function(id, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":center:" + id + ":systems";
    },
    user_centers: function(uid, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":uid:" + uid + ":centers";
    },
    system_key: function(app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":system";
    },
    system_description: function(id, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":system:" + id + ":description";
    },
    system_components: function(id, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":system:" + id + ":components";
    },
    system_linpack: function(id, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":system:" + id + ":linpack";
    },
    user_systems: function(uid, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":uid:" + uid + ":systems";
    },
    component_key: function(app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":component";
    },
    component_description: function(id, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":component:" + id + ":";
    },
    linpack_key: function(app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":linpack";
    },
    linpack_description: function(id, app) {
      if (app == null) {
        app = this.app;
      }
      return "" + app + ":linpack:" + id;
    }
  };

}).call(this);
